/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as ReviewsRouteImport } from './routes/reviews';
import { Route as LoginRouteImport } from './routes/login';
import { Route as HowItWorksRouteImport } from './routes/how-it-works';
import { Route as FeaturesRouteImport } from './routes/features';
import { Route as DoctorRouteImport } from './routes/doctor';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as CompareRouteImport } from './routes/compare';
import { Route as BookRouteImport } from './routes/book';
import { Route as BillingRouteImport } from './routes/billing';
import { Route as AiAssistantRouteImport } from './routes/ai-assistant';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as HospitalsIndexRouteImport } from './routes/hospitals.index';
import { Route as HospitalsHospitalIdRouteImport } from './routes/hospitals.$hospitalId';
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings';
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved';
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews';
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard.appointments';
import { Route as DashboardAdminPricingRouteImport } from './routes/dashboard.admin.pricing';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any);
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any);
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any);
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any);
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any);
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any);
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const HospitalsIndexRoute = HospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRouteImport,
} as any);
const HospitalsHospitalIdRoute = HospitalsHospitalIdRouteImport.update({
  id: '/hospitals/$hospitalId',
  path: '/hospitals/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAdminPricingRoute = DashboardAdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => DashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/admin': typeof AdminRoute;
  '/ai-assistant': typeof AiAssistantRoute;
  '/billing': typeof BillingRoute;
  '/book': typeof BookRoute;
  '/compare': typeof CompareRoute;
  '/contact': typeof ContactRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/doctor': typeof DoctorRoute;
  '/features': typeof FeaturesRoute;
  '/how-it-works': typeof HowItWorksRoute;
  '/login': typeof LoginRoute;
  '/reviews': typeof ReviewsRoute;
  '/signup': typeof SignupRoute;
  '/dashboard/appointments': typeof DashboardAppointmentsRoute;
  '/dashboard/reviews': typeof DashboardReviewsRoute;
  '/dashboard/saved': typeof DashboardSavedRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute;
  '/hospitals/': typeof HospitalsIndexRoute;
  '/dashboard/admin/pricing': typeof DashboardAdminPricingRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/admin': typeof AdminRoute;
  '/ai-assistant': typeof AiAssistantRoute;
  '/billing': typeof BillingRoute;
  '/book': typeof BookRoute;
  '/compare': typeof CompareRoute;
  '/contact': typeof ContactRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/doctor': typeof DoctorRoute;
  '/features': typeof FeaturesRoute;
  '/how-it-works': typeof HowItWorksRoute;
  '/login': typeof LoginRoute;
  '/reviews': typeof ReviewsRoute;
  '/signup': typeof SignupRoute;
  '/dashboard/appointments': typeof DashboardAppointmentsRoute;
  '/dashboard/reviews': typeof DashboardReviewsRoute;
  '/dashboard/saved': typeof DashboardSavedRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute;
  '/hospitals': typeof HospitalsIndexRoute;
  '/dashboard/admin/pricing': typeof DashboardAdminPricingRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/admin': typeof AdminRoute;
  '/ai-assistant': typeof AiAssistantRoute;
  '/billing': typeof BillingRoute;
  '/book': typeof BookRoute;
  '/compare': typeof CompareRoute;
  '/contact': typeof ContactRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/doctor': typeof DoctorRoute;
  '/features': typeof FeaturesRoute;
  '/how-it-works': typeof HowItWorksRoute;
  '/login': typeof LoginRoute;
  '/reviews': typeof ReviewsRoute;
  '/signup': typeof SignupRoute;
  '/dashboard/appointments': typeof DashboardAppointmentsRoute;
  '/dashboard/reviews': typeof DashboardReviewsRoute;
  '/dashboard/saved': typeof DashboardSavedRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute;
  '/hospitals/': typeof HospitalsIndexRoute;
  '/dashboard/admin/pricing': typeof DashboardAdminPricingRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/billing'
    | '/book'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/reviews'
    | '/signup'
    | '/dashboard/appointments'
    | '/dashboard/reviews'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/hospitals/$hospitalId'
    | '/hospitals/'
    | '/dashboard/admin/pricing';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/billing'
    | '/book'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/reviews'
    | '/signup'
    | '/dashboard/appointments'
    | '/dashboard/reviews'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/hospitals/$hospitalId'
    | '/hospitals'
    | '/dashboard/admin/pricing';
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/billing'
    | '/book'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/reviews'
    | '/signup'
    | '/dashboard/appointments'
    | '/dashboard/reviews'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/hospitals/$hospitalId'
    | '/hospitals/'
    | '/dashboard/admin/pricing';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AdminRoute: typeof AdminRoute;
  AiAssistantRoute: typeof AiAssistantRoute;
  BillingRoute: typeof BillingRoute;
  BookRoute: typeof BookRoute;
  CompareRoute: typeof CompareRoute;
  ContactRoute: typeof ContactRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  DoctorRoute: typeof DoctorRoute;
  FeaturesRoute: typeof FeaturesRoute;
  HowItWorksRoute: typeof HowItWorksRoute;
  LoginRoute: typeof LoginRoute;
  ReviewsRoute: typeof ReviewsRoute;
  SignupRoute: typeof SignupRoute;
  HospitalsHospitalIdRoute: typeof HospitalsHospitalIdRoute;
  HospitalsIndexRoute: typeof HospitalsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reviews': {
      id: '/reviews';
      path: '/reviews';
      fullPath: '/reviews';
      preLoaderRoute: typeof ReviewsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/how-it-works': {
      id: '/how-it-works';
      path: '/how-it-works';
      fullPath: '/how-it-works';
      preLoaderRoute: typeof HowItWorksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/features': {
      id: '/features';
      path: '/features';
      fullPath: '/features';
      preLoaderRoute: typeof FeaturesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/doctor': {
      id: '/doctor';
      path: '/doctor';
      fullPath: '/doctor';
      preLoaderRoute: typeof DoctorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contact': {
      id: '/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/compare': {
      id: '/compare';
      path: '/compare';
      fullPath: '/compare';
      preLoaderRoute: typeof CompareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/book': {
      id: '/book';
      path: '/book';
      fullPath: '/book';
      preLoaderRoute: typeof BookRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/billing': {
      id: '/billing';
      path: '/billing';
      fullPath: '/billing';
      preLoaderRoute: typeof BillingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ai-assistant': {
      id: '/ai-assistant';
      path: '/ai-assistant';
      fullPath: '/ai-assistant';
      preLoaderRoute: typeof AiAssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/hospitals/': {
      id: '/hospitals/';
      path: '/hospitals';
      fullPath: '/hospitals/';
      preLoaderRoute: typeof HospitalsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/hospitals/$hospitalId': {
      id: '/hospitals/$hospitalId';
      path: '/hospitals/$hospitalId';
      fullPath: '/hospitals/$hospitalId';
      preLoaderRoute: typeof HospitalsHospitalIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/settings': {
      id: '/dashboard/settings';
      path: '/settings';
      fullPath: '/dashboard/settings';
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/saved': {
      id: '/dashboard/saved';
      path: '/saved';
      fullPath: '/dashboard/saved';
      preLoaderRoute: typeof DashboardSavedRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/reviews': {
      id: '/dashboard/reviews';
      path: '/reviews';
      fullPath: '/dashboard/reviews';
      preLoaderRoute: typeof DashboardReviewsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/appointments': {
      id: '/dashboard/appointments';
      path: '/appointments';
      fullPath: '/dashboard/appointments';
      preLoaderRoute: typeof DashboardAppointmentsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/admin/pricing': {
      id: '/dashboard/admin/pricing';
      path: '/admin/pricing';
      fullPath: '/dashboard/admin/pricing';
      preLoaderRoute: typeof DashboardAdminPricingRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute;
  DashboardReviewsRoute: typeof DashboardReviewsRoute;
  DashboardSavedRoute: typeof DashboardSavedRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardAdminPricingRoute: typeof DashboardAdminPricingRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardAdminPricingRoute: DashboardAdminPricingRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  BillingRoute: BillingRoute,
  BookRoute: BookRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DoctorRoute: DoctorRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
  HospitalsHospitalIdRoute: HospitalsHospitalIdRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
